apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 585008079552.dkr.ecr.ap-south-1.amazonaws.com/flask-mysql-app:latest
          ports:
            - containerPort: 5000
          env:
            # 1. DATABASE HOST
            - name: MYSQL_HOST       # Python looks for this
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_HOST       # Matches your ConfigMap Key

            # 2. DATABASE NAME
            - name: MYSQL_DB         # Python looks for this
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_NAME       # Matches your ConfigMap Key

            # 3. DATABASE USER
            - name: MYSQL_USER       # Python looks for this
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_USER       # Matches your ConfigMap Key

            # 4. DATABASE PASSWORD
            - name: MYSQL_PASSWORD   # Python looks for this
              valueFrom:
                secretKeyRef:
                  name: mysql-secret # ðŸŸ¢ CORRECTED: Matches 'kubectl get secret' output
                  key: MYSQL_PASSWORD # Matches key from your earlier mysql setup
